# Generated by Django 3.2.3 on 2023-08-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('User', 'CustomUser')
    ]
