# Generated by Django 3.2.3 on 2023-08-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_follower_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Subscription',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='users.Subscription', verbose_name='Является подписчиком'),
        ),
    ]
