# Generated by Django 3.2.3 on 2023-08-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подписаться на автора'),
        ),
    ]
