# Generated by Django 3.2.3 on 2023-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recipes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество рецептов пользователя'),
        ),
    ]
