# Generated by Django 3.2.3 on 2023-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_recipes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='recipes_count',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscripting'),
        ),
    ]
