# Generated by Django 3.2.3 on 2023-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подписаться на автора'),
        ),
    ]
