version: '3'

volumes:
  pg_data_production_food:
  static_volume_food:
  media_volume_food:

services:

  db:
    container_name: foodgram_db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data_production_food:/var/lib/postgresql/data/
    restart: always

  backend:
    container_name: foodgram_backend
    image: axeunder/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume_food:/backend_static/
      - media_volume_food:/backend_media/
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    image: axeunder/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_food:/frontend_static/

  gateway:
    container_name: foodgram_gateway
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ../foodgram/nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ../foodgram/frontend/build:/usr/share/nginx/html/
      - ../foodgram/docs/:/usr/share/nginx/html/api/docs/
      - static_volume_food:/staticfiles/
      - media_volume_food:/var/html/media/
    depends_on:
      - backend
      - frontend