version: '3'

services:

  db:
    container_name: foodgram_db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data_production_food:/var/lib/postgresql/data/
    restart: always

  backend:
    container_name: foodgram_backend
    image: axeunder/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume_food:/backend_static/app/static/
      - media_volume_food:/app/media/
    depends_on:
      - db
    restart: always

  frontend:
    container_name: foodgram_frontend
    image: axeunder/foodgram_frontend:latest
    volumes:
      - static_volume_food:/frontend_static/app/build/
    restart: on-failure

  gateway:
    container_name: foodgram_gateway
    image: nginx:1.19.3
    ports:
      - "8080:443"
    volumes:
      - ../infra/nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume_food:/staticfiles/
      - media_volume_food:/var/html/media/
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  pg_data_production_food:
  static_volume_food:
  media_volume_food: