version: '3'

volumes:
  pg_data_food:
  static_volume_food:
  media_volume_food:
  docs_food:

services:

  db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data_food:/var/lib/postgresql/data/
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static_volume_food:/backend_static/
      - media_volume_food:/backend_media/
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_volume_food:/frontend_static/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_volume_food:/staticfiles/
      - docs_food:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always