version: '3'

volumes:
  pg_data_production_food:
  static_volume_food:
  media_volume_food:

services:

  db:
    image: postgres:13.0-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_production_food:/var/lib/postgresql/data/
    restart: always

  backend:
    image: axeunder/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume_food:/backend_static/
      - media_volume_food:/backend_media/
    depends_on:
      - db

  frontend:
    image: axeunder/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_food:/frontend_static/

  gateway:
    image: axeunder/foodgram_gateway:latest
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ./ssl/:/etc/nginx/ssl/
      - static_volume_food:/staticfiles/
      - media_value:/var/html/media/