# Generated by Django 3.2.3 on 2023-08-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_is_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(blank=True, help_text='Загрузите картинку', null=True, verbose_name='Ссылка на картинку на сайте'),
        ),
    ]
