# Generated by Django 3.2.3 on 2023-08-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shopping_cart',
            new_name='is_shopping_cart',
        ),
    ]
