# Generated by Django 3.2.3 on 2023-08-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230813_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWithRecipes',
        ),
    ]
