# Generated by Django 3.2.3 on 2023-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='rescipes/', verbose_name='Ссылка на картинку на сайте'),
        ),
    ]
