# Generated by Django 3.2.3 on 2023-08-30 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Введите время готовки (мин.)', validators=[django.core.validators.MinValueValidator(1, 'Время готовки не должно быть меньше минуты'), django.core.validators.MaxValueValidator(1440, 'Время готовки не должно быть больше суток')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество не должно быть меньше 1'), django.core.validators.MaxValueValidator(100000, 'Количество не должно быть больше 100.000')], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
    ]
